version: '3.8'

services:
  app:
    image: nestjs-docker:local
    container_name: nestjs-docker
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 9229:9229
    expose:
      - 3000
      - 9229
    volumes:
      - .:/app
